# Purpose: Defines the ServiceAccount used by both the API and the Collector pods.
# This identity is used to associate RBAC permissions.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubechargeback-sa
  namespace: kubechargeback