apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chargeback-api
  namespace: kubechargeback
spec:
  to:
    kind: Service
    name: chargeback-api
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
